#You can run this file with sudo docker build . when in the same directory

#start from a linux version
FROM ubuntu

#I need the nodejs runtime. I can use apt. Remember -y for interactive commands or the build will fail
RUN apt update && apt install nodejs -y

